stages:
  - build-frontend
  - deploy-frontend
  - build-nginx

default:
  tags:
    - snack-test

build-frontend-job:
  stage: build-frontend
  script:
    - cd ./src/frontend
    - docker build . -t frontenv
    - mkdir build
    - cd build
    - docker run -v "$(pwd):/src/front/build" --name frontenv frontenv
    - cd ..
    - tar -cvf front.tar ./build/*

  after_script:
    - cd ./src/frontend
    - chmod 777 build
    - rm -rf build
    - docker rm frontenv

  artifacts:
    paths:
      - ./src/frontend/front.tar

deploy-frontend-job:
  stage: deploy-frontend

  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd ./src/frontend
    - yes | scp front.tar ec2-user@snackstyling.com:/snack-style/frontend

build-nginx-job:
  stage: build-nginx
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd ./src/nginx
    - docker build -t nginx ./
    - docker save -o nginx.tar nginx
    - yes | scp nginx.tar ec2-user@snackstyling.com:/snack-style/image
