default:
  tags:
    - snack-test
  only:
    - master
    - feature/pipeline
    
stages:
  - build
  - test
  - package
  - deploy

build-spring:
  stage: build
  script:
    - cd src/backend/spring
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    paths:
      - src/backend/spring/build/libs/*.jar 

test-spring:
  stage: test 
  script:
    - cd src/backend/spring
    - ./gradlew test
  artifacts:
    paths:
      - src/backend/spring/build/libs/*.jar 

package-spring:
  stage: package
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
  script:
    - cd src/backend/spring
    - docker build -t spring ./
    - docker save -o spring.tar spring
    - scp spring.tar ec2-user@13.209.54.85:/tmp
  artifacts:
    paths:
      - src/backend/spring/build/libs/*.jar 

deploy-spring:
  stage: deploy
  tags:
    - snack-service
  script:
    - sudo docker stop spring-service
    - sudo docker rm spring-service
    - sudo docker image rm spring
    - sudo docker load -i /tmp/spring.tar
    - sudo docker run --env-file=/tmp/.env -d --name spring-service -p 80:8080 spring
