stages:
  - build-frontend
  - package-frontend
  - deploy-frontend
  - build-nginx
  - deploy-nginx

default:
  tags:
    - snack-test

build-frontend-job:
  stage: build-frontend
  script:
    - cd ./src/frontend
    - docker build . -t frontenv
    - mkdir result
    - cd result
    - docker run --rm -v "$(pwd):/src/frontend/result" frontenv

  artifacts:
    paths:
      - ./src/frontend/result/front.tar

deploy-frontend:
  stage: deploy-frontend
  tags:
    - snack-service
  script:
    - sudo tar -xvf ./src/frontend/result/front.tar -C /snack-style/frontend

build-nginx-job:
  stage: build-nginx
  script:
    - cd ./src/nginx
    - docker build -t nginx ./
    - docker save -o nginx.tar nginx

  artifacts:
    paths:
      - ./src/nginx/nginx.tar

deploy-nginx-job:
  stage: deploy-nginx
  tags:
    - snack-service
  script:
    - sudo docker stop nginx || true
    - sudo docker rm nginx || true
    - sudo docker image rm nginx || true
    - sudo docker load -i ./src/nginx/nginx.tar
    - sudo docker run -d --name nginx -p 80:8080 nginx
