stages:
  - build-frontend
  - deploy-frontend
  - build-nginx

default:
  tags:
    - snack-test

build-frontend-job:
  stage: build-frontend
  script:
    - cd ./src/frontend
    - docker build . -t frontenv
    - mkdir file
    - cd file
    - docker run --rm -v "$(pwd):/src/frontend/file" --name frontenv frontenv

  artifacts:
    paths:
      - ./src/frontend/file/front.tar

deploy-frontend-job:
  stage: deploy-frontend

  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd ./src/frontend
    - yes | scp front.tar ec2-user@snackstyling.com:/snack-style/frontend

build-nginx-job:
  stage: build-nginx
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd ./src/nginx
    - docker build -t nginx ./
    - docker save -o nginx.tar nginx
    - yes | scp nginx.tar ec2-user@snackstyling.com:/snack-style/image
