stages:
  - build-frontend
  - deploy-frontend
  - build-nginx

build-frontend-job:
  stage: build-frontend
  script:
    - cd ./src/frontend
    - docker build . -t frontenv
    - docker images
    - docker run -v build:/src/front/build frontenv
    - tar -cvf front.tar build/*

  artifacts:
    paths:
      - front.tar

deploy-frontend-job:
  stage: deploy-frontend

  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd ./src/frontend
    - scp front.tar ec2-user@3.34.30.156:/snack-style/frontend

build-nginx-job:
  stage: build-nginx
  before_script:
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"

  script:
    - cd src/nginx
    - docker build -t nginx ./
    - docker save -o nginx.tar nginx
    - scp spring.tar ec2-user@3.34.30.156:/snack-style/image
