version: "3.9"
services:
  backend-django:
    build: ../src/backend/django
    ports:
      - "8000:8000"
    volumes:
    - .:/home/appuser/src
  db-mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stylingapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - 3306:3306
  db-redis:
    image: redis
    ports:
      - 6379:6379
  backend-spring:
    build: ../src/backend/spring
    platform: linux/amd64
    ports:
      - 8080:8080
    links:
      - db-mysql
      - backend-django
      - db-redis
    depends_on:
      - db-mysql
      - backend-django
      - db-redis
